const KEY="ca-final-study-tracker-v2";
const base={settings:{attempt:"November 2027",examDate:""},subjects:[
{id:"FR",code:"FR",name:"Financial Reporting",mode:"lecture",desc:"Batch 9 lectures + 3 revisions"},
{id:"AFM",code:"AFM",name:"Advanced Financial Management",mode:"lecture",desc:"Regular Batch 9 lectures + 3 revisions"},
{id:"AUD",code:"AUD",name:"Audit",mode:"lecture",desc:"Lectures + Fast Track where specified"},
{id:"DT",code:"DT",name:"Direct Tax",mode:"self",desc:"Self-study for now; lectures can be added later"},
{id:"IDT",code:"IDT",name:"Indirect Tax",mode:"self",desc:"Self-study for now; lectures can be added later"},
{id:"IBS",code:"IBS",name:"Integrated Business Solutions",mode:"self",desc:"Self-study / case-study based"}],items:[],resources:[]};
let state=load(),view="dashboard",filter="ALL";
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(base)}catch(e){return structuredClone(base)}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function subj(id){return state.subjects.find(s=>s.id===id)}
function arr(id){return state.items.filter(i=>i.subject===id)}
function secs(v){if(!v)return 0;let p=String(v).trim().split(":").map(Number);if(p.some(isNaN))return 0;return p.length===3?p[0]*3600+p[1]*60+p[2]:p.length===2?p[0]*60+p[1]:Number(v)*60}
function time(s){if(!s)return"—";let h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return(h?h+"h ":"")+m+"m"+(h?"":" "+x+"s")}
function percentage(a){return a.length?Math.round(a.reduce((n,x)=>n+(x.progress||0),0)/a.length):0}
function revPct(r){let a=state.items.filter(x=>x.rev);return a.length?Math.round(a.reduce((n,x)=>n+(x.rev[r]||0),0)/a.length):0}
function toast(m){let d=document.createElement("div");d.className="toast";d.textContent=m;document.body.appendChild(d);setTimeout(()=>d.remove(),2000)}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===b));render()});
document.getElementById("quick").onclick=()=>itemModal();
document.getElementById("backup").onclick=exportData;
function render(){document.getElementById("title").textContent={dashboard:"Dashboard",subjects:"Subjects",lectures:"Lectures",revisions:"Revisions",resources:"Resources",import:"Import Centre",analytics:"Analytics",settings:"Settings"}[view];({dashboard:dashboard,subjects:subjects,lectures:lectures,revisions:revisions,resources:resources,import:imports,analytics:analytics,settings:settings}[view]||dashboard)()}
function stat(a,b,c){return '<div class="stat"><small>'+a+'</small><b>'+b+'</b><span class="muted">'+c+'</span></div>'}
function dashboard(){let ls=state.items.filter(i=>i.kind==="lecture"),next=ls.filter(i=>(i.progress||0)<100).sort((a,b)=>(a.progress||0)-(b.progress||0)).slice(0,5);document.getElementById("content").innerHTML='<div class="grid stats">'+stat("Lecture progress",percentage(ls)+"%","Imported lecture items")+stat("Total lecture hours",time(ls.reduce((n,x)=>n+(x.duration||0),0)),"Across FR, AFM and Audit")+stat("Revision 1",revPct("r1")+"%","Conceptual revision")+stat("Revision 2",revPct("r2")+"%","Exam-oriented revision")+'</div><div class="section"><div><h2>CA Final Preparation</h2><p>November 2027 • lecture and self-study model</p></div></div><div class="grid subjects">'+state.subjects.map(card).join("")+'</div><div class="card" style="padding:19px;margin-top:18px"><div class="section"><div><h2>Continue Studying</h2><p>Lowest-progress lecture items</p></div></div>'+(next.length?'<div class="list">'+next.map(i=>'<div class="item"><div><b>'+esc(i.title)+'</b><small>'+esc(subj(i.subject).code)+' • '+time(i.duration)+'</small></div><button class="ghost" onclick="editItem(\''+i.id+'\')">Open</button></div>').join("")+'</div>':'<div class="empty">Import your lecture files from Import Centre to populate this list.</div>')+'</div>'}
function card(s){let a=arr(s.id),p=s.mode==="lecture"?percentage(a):0;return '<div class="card subject" ><div class="row"><div><div class="code">'+s.code+'</div><h3>'+esc(s.name)+'</h3><span class="muted">'+esc(s.desc)+'</span></div><span class="tag '+(s.mode==="self"?"self":"")+'">'+(s.mode==="lecture"?"Lectures":"Self-study")+'</span></div><div class="progress"><i style="width:'+p+'%"></i></div><div class="row"><small>'+p+'% progress</small><small>'+a.length+' items</small></div><div style="margin-top:12px"><button class="ghost" onclick="openSubject(\''+s.id+'\')">Open</button></div></div>'}
function openSubject(id){filter=id;view="lectures";render()}
function subjects(){document.getElementById("content").innerHTML='<div class="grid subjects">'+state.subjects.map(card).join("")+'</div>'}
function lectures(){let a=state.items.filter(i=>i.kind==="lecture"&&(filter==="ALL"||i.subject===filter));document.getElementById("content").innerHTML='<div class="filters"><select class="select" id="sf"><option value="ALL">All lecture subjects</option>'+state.subjects.filter(s=>s.mode==="lecture").map(s=>'<option value="'+s.id+'" '+(filter===s.id?"selected":"")+'>'+s.code+' — '+esc(s.name)+'</option>').join("")+'</select><input class="input" id="search" placeholder="Search lecture / chapter / concept"><select class="select" id="status"><option value="all">All status</option><option value="todo">Not started</option><option value="doing">In progress</option><option value="done">Completed</option></select><button class="primary" onclick="view=\'import\';render()">Import more</button></div><div class="card"><div class="tablewrap"><table class="table"><thead><tr><th>Subject</th><th>Chapter / Day</th><th>Lecture</th><th>Duration</th><th>Progress</th><th>R1/R2/R3</th><th></th></tr></thead><tbody id="rows">'+lectureRows(a)+'</tbody></table></div></div>';document.getElementById("sf").onchange=e=>{filter=e.target.value;lectures()};document.getElementById("search").oninput=filterRows;document.getElementById("status").onchange=filterRows}
function lectureRows(a){return a.length?a.map(i=>'<tr data-q="'+esc((i.title+" "+i.chapter+" "+i.concepts).toLowerCase())+'" data-s="'+(i.progress>=100?"done":i.progress>0?"doing":"todo")+'"><td><b>'+esc(subj(i.subject).code)+'</b></td><td>'+esc(i.chapter||i.day||"—")+'</td><td>'+esc(i.title)+'</td><td>'+time(i.duration)+'</td><td><div class="progress" style="width:120px;margin:0 0 4px"><i style="width:'+(i.progress||0)+'%"></i></div><small>'+(i.progress||0)+'%</small></td><td><small>R1 '+(i.rev?.r1||0)+'% • R2 '+(i.rev?.r2||0)+'% • R3 '+(i.rev?.r3||0)+'%</small></td><td><button class="ghost" onclick="editItem(\''+i.id+'\')">Open</button></td></tr>').join(""):'<tr><td colspan="7"><div class="empty">No lecture items. Import your PDF/Excel.</div></td></tr>'}
function filterRows(){let q=document.getElementById("search").value.toLowerCase(),s=document.getElementById("status").value;document.querySelectorAll("#rows tr").forEach(r=>r.style.display=((r.dataset.q||"").includes(q)&&(s==="all"||r.dataset.s===s))?"":"none")}
function revisions(){let a=state.items.filter(i=>filter==="ALL"||i.subject===filter);document.getElementById("content").innerHTML='<div class="filters"><select class="select" id="rf"><option value="ALL">All subjects</option>'+state.subjects.map(s=>'<option value="'+s.id+'" '+(filter===s.id?"selected":"")+'>'+s.code+' — '+esc(s.name)+'</option>').join("")+'</select></div><div class="grid subjects">'+[['r1','Revision 1','Conceptual revision'],['r2','Revision 2','Exam-oriented revision'],['r3','Revision 3','Rapid final revision']].map(x=>'<div class="card subject"><div class="row"><div><h3>'+x[1]+'</h3><span class="muted">'+x[2]+'</span></div><b>'+revPct(x[0])+'%</b></div><div class="progress"><i style="width:'+revPct(x[0])+'%"></i></div><div class="list">'+a.slice(0,30).map(i=>'<label class="item"><div><b>'+esc(i.title)+'</b><small>'+esc(subj(i.subject).code)+'</small></div><input type="checkbox" '+(i.rev?.[x[0]]===100?"checked":"")+' onchange="toggleRev(\''+i.id+'\',\''+x[0]+'\',this.checked)"></label>').join("")+'</div></div>').join("")+'</div>';document.getElementById("rf").onchange=e=>{filter=e.target.value;revisions()}}
function resources(){document.getElementById("content").innerHTML='<div class="section"><div><h2>Resource Library</h2><p>Google Drive, YouTube, ICAI, RTP, MTP, notes and question banks.</p></div><button class="primary" onclick="resourceModal()">+ Add Resource</button></div><div class="card" style="padding:16px">'+(state.resources.length?'<div class="list">'+state.resources.map(r=>'<div class="item"><div><b>'+esc(r.name)+'</b><small>'+esc(subj(r.subject)?.code||r.subject||"General")+' • '+esc(r.type||"Resource")+'</small></div><a class="primary" target="_blank" rel="noopener" href="'+esc(r.url)+'">Open</a></div>').join("")+'</div>':'<div class="empty">No resources added yet.</div>')+'</div>'}
function imports(){document.getElementById("content").innerHTML='<div class="card" style="padding:20px"><div class="section"><div><h2>Bulk Import Centre</h2><p>FR/AFM use table-of-contents PDFs; Audit uses a different lecture sheet. The importer normalizes both.</p></div></div><div class="grid subjects">'+state.subjects.map(s=>'<button class="card subject" style="text-align:left;border:2px solid '+(filter===s.id?"#818cf8":"var(--line)")+'" onclick="selectImport(\''+s.id+'\')"><div class="code">'+s.code+'</div><h3>'+esc(s.name)+'</h3><span class="muted">'+(s.mode==="lecture"?"Upload PDF / Excel / CSV":"Self-study — add items manually")+'</span></button>').join("")+'</div><div id="ip" style="margin-top:18px">'+(filter!=="ALL"?importBox(subj(filter)):'<div class="empty">Select a subject above.</div>')+'</div></div>'}
function selectImport(id){filter=id;imports()}
function importBox(s){return '<div class="import"><h3>Import '+esc(s.name)+'</h3><p>'+(s.mode==="lecture"?"Upload your actual source file. You will see a preview before anything is imported.":"Add chapters/case studies/resources manually. You can add lectures later.")+'</p>'+(s.mode==="lecture"?'<label class="file">Choose PDF / Excel / CSV<input id="file" type="file" accept=".pdf,.xlsx,.xls,.csv" hidden></label>':'<button class="primary" onclick="itemModal(\''+s.id+'\')">+ Add Self-study Item</button>')+'<div id="importMsg"></div></div>'}
document.addEventListener("change",e=>{if(e.target.id==="file"&&e.target.files[0])readFile(e.target.files[0])});
async function readFile(f){let msg=document.getElementById("importMsg");msg.innerHTML='<p>Reading '+esc(f.name)+'…</p>';try{let rows=f.name.toLowerCase().endsWith(".pdf")?await pdfRows(f):await excelRows(f);if(!rows.length)throw Error("No recognizable rows found. Try the Excel/CSV version or adjust the source format.");preview(rows,f.name)}catch(e){msg.innerHTML='<p style="color:var(--red)">'+esc(e.message)+'</p>'}}
async function excelRows(f){let wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),sh=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(sh,{header:1,defval:""});if(!a.length)return[];let h=a[0].map(x=>String(x).trim());return a.slice(1).filter(r=>r.some(Boolean)).map(r=>{let o={};h.forEach((k,i)=>o[k]=r[i]);return norm(o)}).filter(x=>x.title||x.no)}
async function pdfRows(f){let pdf=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.5.136/pdf.min.mjs"),doc=await pdf.getDocument({data:await f.arrayBuffer()}).promise,lines=[];for(let p=1;p<=doc.numPages;p++){let tc=await (await doc.getPage(p)).getTextContent();lines.push(tc.items.map(x=>x.str).join(" "))}let out=[];for(let line of lines.join("\n").split("\n")){line=line.trim();if(filter==="AUD"){let m=line.match(/^(\\d+)\\s+(.+?)\\s+(\\d{1,2}:\\d{2}:\\d{2})\\s+(.+)$/);if(m)out.push({no:m[1],title:m[2],duration:secs(m[3]),category:m[4]})}else{let m=line.match(/^(Day\\s+.+?)\\s+(\\d+_\\d+[a-z]?)_([^\\d]+?)\\s+(\\d{1,2}:\\d{2}:\\d{2})\\s+([\\d.]+)\\s*(.*)$/i);if(m)out.push({day:m[1],no:m[2],title:m[3].trim(),duration:secs(m[4]),size:m[5],raw:m[6]})}}return out.map(norm).filter(x=>x.title||x.no)}
function key(s){return String(s).toLowerCase().replace(/[^a-z0-9]/g,"")}
function norm(o){let get=a=>{let k=Object.keys(o).find(x=>a.includes(key(x)));return k?o[k]:""};return{no:String(get(["lectureno","lecturenumber","lecture","srno","sr"])).trim(),title:String(get(["lecturename","lecturetitle","title","topic","classname"])).trim(),day:String(get(["day","days","chapter","module"])).trim(),chapter:String(get(["chapter","day","days","module"])).trim(),duration:secs(get(["duration","time","length"])),category:String(get(["category"])).trim(),concepts:String(get(["concept","concepts","topiccovered"])).trim(),questions:String(get(["questionnumbers","questions","questionnumber"])).trim(),board:String(get(["boardnotespageno","boardnotes","notespageno"])).trim()}}
function preview(rows,name){let m=document.createElement("div");m.className="modalbg";m.innerHTML='<div class="modalbox"><div class="modalhead"><div><h2>Import Preview</h2><p class="muted">'+esc(name)+' • '+rows.length+' rows detected • '+esc(subj(filter).name)+'</p></div><button class="close">×</button></div><div class="tablewrap"><table class="table"><thead><tr><th>No.</th><th>Day/Chapter</th><th>Lecture</th><th>Duration</th><th>Category</th><th>Concepts</th></tr></thead><tbody>'+rows.slice(0,80).map((r,i)=>'<tr><td>'+esc(r.no)+'</td><td>'+esc(r.chapter||r.day)+'</td><td>'+esc(r.title)+'</td><td>'+time(r.duration)+'</td><td>'+esc(r.category)+'</td><td>'+esc(r.concepts)+'</td></tr>').join("")+'</tbody></table></div><div class="actions"><button class="ghost" id="cancel">Cancel</button><button class="primary" id="doImport">Import '+rows.length+' rows</button></div></div>';document.getElementById("modal").appendChild(m);m.querySelector(".close").onclick=()=>m.remove();m.querySelector("#cancel").onclick=()=>m.remove();m.querySelector("#doImport").onclick=()=>{let seen=new Set(state.items.map(x=>x.key));let add=0;rows.forEach((r,n)=>{let k=[filter,r.no,r.title,r.day].join("|").toLowerCase();if(seen.has(k))return;state.items.push({id:crypto.randomUUID(),key:k,subject:filter,kind:"lecture",no:r.no||String(n+1),title:r.title||"Lecture "+(n+1),day:r.day||"",chapter:r.chapter||r.day||"",duration:r.duration||0,category:r.category||"",concepts:r.concepts||"",questions:r.questions||"",board:r.board||"",progress:0,rev:{r1:0,r2:0,r3:0}});add++});save();m.remove();toast(add+" rows imported");view="lectures";render()}}
function itemModal(subjectId){let s=subjectId||filter;if(s==="ALL")s="FR";let m=document.createElement("div");m.className="modalbg";m.innerHTML='<div class="modalbox"><div class="modalhead"><h2>Add Study Item</h2><button class="close">×</button></div><div class="mapping"><div class="field"><label>Subject</label><select id="ms" class="select">'+state.subjects.map(x=>'<option value="'+x.id+'" '+(x.id===s?"selected":"")+'>'+x.code+' — '+esc(x.name)+'</option>').join("")+'</select></div><div class="field"><label>Type</label><select id="mk" class="select"><option value="lecture">Lecture</option><option value="study">Self-study</option></select></div><div class="field"><label>Item / Lecture No.</label><input id="mn" class="input"></div><div class="field"><label>Title</label><input id="mt" class="input"></div><div class="field"><label>Chapter / Module</label><input id="mc" class="input"></div><div class="field"><label>Duration</label><input id="md" class="input" placeholder="2:10:30"></div><div class="field"><label>Progress %</label><input id="mp" class="input" type="number" min="0" max="100" value="0"></div><div class="field"><label>Resource URL</label><input id="mu" class="input" placeholder="Google Drive / YouTube / ICAI"></div></div><div class="actions"><button class="ghost" id="cancel">Cancel</button><button class="primary" id="save">Save</button></div></div>';document.getElementById("modal").appendChild(m);m.querySelector(".close").onclick=()=>m.remove();m.querySelector("#cancel").onclick=()=>m.remove();m.querySelector("#save").onclick=()=>{let title=m.querySelector("#mt").value.trim();if(!title)return toast("Title is required");let it={id:crypto.randomUUID(),key:"manual-"+crypto.randomUUID(),subject:m.querySelector("#ms").value,kind:m.querySelector("#mk").value,no:m.querySelector("#mn").value,title,chapter:m.querySelector("#mc").value,duration:secs(m.querySelector("#md").value),progress:Number(m.querySelector("#mp").value)||0,url:m.querySelector("#mu").value.trim(),rev:{r1:0,r2:0,r3:0}};state.items.push(it);if(it.url)state.resources.push({id:crypto.randomUUID(),subject:it.subject,name:title,type:"Resource",url:it.url});save();m.remove();toast("Saved");render()}}
function editItem(id){let i=state.items.find(x=>x.id===id);if(!i)return;let m=document.createElement("div");m.className="modalbg";m.innerHTML='<div class="modalbox"><div class="modalhead"><div><h2>Edit Study Item</h2><p class="muted">'+esc(subj(i.subject).name)+'</p></div><button class="close">×</button></div><div class="mapping"><div class="field"><label>Title</label><input id="et" class="input" value="'+esc(i.title)+'"></div><div class="field"><label>Chapter / Day</label><input id="ec" class="input" value="'+esc(i.chapter||i.day)+'"></div><div class="field"><label>Progress %</label><input id="ep" class="input" type="number" min="0" max="100" value="'+(i.progress||0)+'"></div><div class="field"><label>Resource URL</label><input id="eu" class="input" value="'+esc(i.url||"")+'"></div></div><div class="field" style="margin-top:12px"><label>Notes / Concepts</label><textarea id="en" class="textarea">'+esc(i.notes||i.concepts||"")+'</textarea></div><div class="actions"><button class="ghost" id="del">Delete</button><button class="primary" id="save">Save</button></div></div>';document.getElementById("modal").appendChild(m);m.querySelector(".close").onclick=()=>m.remove();m.querySelector("#del").onclick=()=>{state.items=state.items.filter(x=>x.id!==id);save();m.remove();render();toast("Deleted")};m.querySelector("#save").onclick=()=>{i.title=m.querySelector("#et").value.trim();i.chapter=m.querySelector("#ec").value.trim();i.progress=Math.max(0,Math.min(100,Number(m.querySelector("#ep").value)||0));i.notes=m.querySelector("#en").value;if(m.querySelector("#eu").value.trim())i.url=m.querySelector("#eu").value.trim();save();m.remove();render();toast("Saved")}}
function toggleRev(id,r,yes){let i=state.items.find(x=>x.id===id);if(i){i.rev=i.rev||{};i.rev[r]=yes?100:0;save();revisions()}}
function resourceModal(){let m=document.createElement("div");m.className="modalbg";m.innerHTML='<div class="modalbox"><div class="modalhead"><h2>Add Resource</h2><button class="close">×</button></div><div class="mapping"><div class="field"><label>Name</label><input id="rn" class="input"></div><div class="field"><label>Subject</label><select id="rs" class="select">'+state.subjects.map(s=>'<option value="'+s.id+'">'+s.code+'</option>').join("")+'</select></div><div class="field"><label>Type</label><select id="rt" class="select"><option>Google Drive</option><option>YouTube</option><option>ICAI</option><option>RTP</option><option>MTP</option><option>Notes</option><option>Question Bank</option><option>Other</option></select></div><div class="field"><label>URL</label><input id="ru" class="input"></div></div><div class="actions"><button class="ghost" id="cancel">Cancel</button><button class="primary" id="save">Save</button></div></div>';document.getElementById("modal").appendChild(m);m.querySelector(".close").onclick=()=>m.remove();m.querySelector("#cancel").onclick=()=>m.remove();m.querySelector("#save").onclick=()=>{let n=m.querySelector("#rn").value.trim(),u=m.querySelector("#ru").value.trim();if(!n||!u)return toast("Name and URL required");state.resources.push({id:crypto.randomUUID(),name:n,subject:m.querySelector("#rs").value,type:m.querySelector("#rt").value,url:u});save();m.remove();render();toast("Resource added")}}
function analytics(){let ls=state.items.filter(i=>i.kind==="lecture");document.getElementById("content").innerHTML='<div class="grid stats">'+stat("Items",state.items.length,"Imported + manual")+stat("Lecture hours",time(ls.reduce((n,x)=>n+(x.duration||0),0)),"FR + AFM + Audit")+stat("R3 progress",revPct("r3")+"%","Rapid revision")+stat("Resources",state.resources.length,"Saved links")+'</div><div class="card" style="padding:19px;margin-top:18px"><h2 style="font-size:16px">Subject Progress</h2><div class="tablewrap"><table class="table"><thead><tr><th>Subject</th><th>Mode</th><th>Items</th><th>Progress</th></tr></thead><tbody>'+state.subjects.map(s=>{let a=arr(s.id),p=s.mode==="lecture"?percentage(a):0;return'<tr><td><b>'+s.code+' — '+esc(s.name)+'</b></td><td>'+s.mode+'</td><td>'+a.length+'</td><td><b>'+p+'%</b><div class="progress"><i style="width:'+p+'%"></i></div></td></tr>'}).join("")+'</tbody></table></div></div>'}
function settings(){document.getElementById("content").innerHTML='<div class="card" style="padding:20px"><h2 style="font-size:16px">Settings</h2><div class="mapping"><div class="field"><label>Attempt</label><input id="attempt" class="input" value="'+esc(state.settings.attempt)+'"></div><div class="field"><label>Exact exam date (optional)</label><input id="date" type="date" class="input" value="'+esc(state.settings.examDate)+'"></div></div><div class="actions"><button class="primary" id="saveSet">Save Settings</button></div></div><div class="card" style="padding:20px;margin-top:18px"><h2 style="font-size:16px">Data Backup</h2><p class="muted">Data is stored in this browser. Export a JSON backup regularly.</p><button class="ghost" onclick="exportData()">Export JSON</button> <label class="file">Restore JSON<input id="restore" type="file" accept=".json" hidden></label></div>';document.getElementById("saveSet").onclick=()=>{state.settings.attempt=document.getElementById("attempt").value;state.settings.examDate=document.getElementById("date").value;save();toast("Settings saved")};document.getElementById("restore").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast("Backup restored")}catch(e){toast("Invalid backup")}};r.readAsText(f)}}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="CA-Final-Nov-2027-Study-Tracker-Backup.json";a.click()}
render();